// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC5lGp4ZK9iQkn_7qcspbikQR7ZPEs9xU',
    appId: '1:486087671100:web:8a1dd2ec1fbf632362f239',
    messagingSenderId: '486087671100',
    projectId: 'phonefirebase-9f78f',
    authDomain: 'phonefirebase-9f78f.firebaseapp.com',
    storageBucket: 'phonefirebase-9f78f.appspot.com',
    measurementId: 'G-25R6QECGFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw2-4_etOyQz8Qc9a-W8yqL7R5zQrpuLk',
    appId: '1:486087671100:android:b40a222b29ae728c62f239',
    messagingSenderId: '486087671100',
    projectId: 'phonefirebase-9f78f',
    storageBucket: 'phonefirebase-9f78f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArxviARF--hwnnHvwBYAM7wyoxYPVG7r4',
    appId: '1:486087671100:ios:9892b17ca615073462f239',
    messagingSenderId: '486087671100',
    projectId: 'phonefirebase-9f78f',
    storageBucket: 'phonefirebase-9f78f.appspot.com',
    iosBundleId: 'com.example.warrantyRegistrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArxviARF--hwnnHvwBYAM7wyoxYPVG7r4',
    appId: '1:486087671100:ios:b4832b5baf6e1c1562f239',
    messagingSenderId: '486087671100',
    projectId: 'phonefirebase-9f78f',
    storageBucket: 'phonefirebase-9f78f.appspot.com',
    iosBundleId: 'com.example.warrantyRegistrationApp.RunnerTests',
  );
}
